// /compress — content codings that misbehave on purpose.
// RFC 9110 §8.4 (Content-Encoding) and §12.5.3 (Accept-Encoding); RFC 1952 (gzip), RFC 1950 (zlib, which
// is what the "deflate" coding means), RFC 1951 (raw DEFLATE, which is what many servers send instead),
// RFC 7932 (br), RFC 8878 (zstd). The document is deterministic and self-describing (64-byte lines, each
// starting with its own offset, like /range), and every flavor response states the plaintext's length and
// SHA-256 in headers, so a client can prove what it decoded. Stateless; the only per-isolate state is a small
// memo of compressed bytes. Helpers (json, bad, intParam, bodyCodeParam, withBase, sleep) come in from index.js.
//
// "The edge" below is Cloudflare's CDN, which sits between the client and this Worker. It is part of the
// experiment, and the family is designed around what it was observed to do (probed live 2026-09-01:
// docs/probe-compress-2026-09-01.txt, docs/spec-compress.md):
//  - it rewrites Accept-Encoding to "gzip, br" before the Worker runs and keeps a NORMALIZED copy of the
//    client's value in request.cf.clientAcceptEncoding: a canonical set in a fixed order, q-values dropped
//    (q=0 included — a refusal never reaches this server), x-gzip and case folded to gzip, "*" and an empty
//    value reported as absent, a value with any non-ASCII byte reported as absent, and zstd dropped from the
//    set entirely (even though it delivers zstd to a client that lists it);
//  - it removes one coding layer it recognizes (gzip, br, zstd) unless that normalized set lists the coding,
//    transcoding the body to identity — cache-control: no-transform notwithstanding — and that transcoding is
//    lossy for broken streams; a second declared layer (double) is delivered regardless;
//  - it decoded zlib deflate for every client probed, including one that asked for it (the deflate flavor
//    exists so that observation stays reproducible);
//  - it passes codings it does not recognize (x-gzip, badhttp) through untouched.
// So: send Accept-Encoding: gzip to receive the gzip flavors as bytes, and read each flavor's edge column
// for what a client without gzip got. The raw Accept-Encoding header is never negotiated from: behind the
// edge it carries no client information, and local wrangler dev has no edge and no clientAcceptEncoding, so
// the negotiating flavors (ok, bomb) only behave as documented against the real host.

const LINE = 64;
const DEFAULT_LENGTH = 4096;
// br and zstd: this runtime has no encoder for either (CompressionStream speaks gzip, deflate and
// deflate-raw only), so their bytes are pre-computed for the default document and its length is fixed.
const FIXED_LENGTH = 4096;
const FIXED_SHA256 = '3bb736fa851dceb1aaaa02c7ee2787f749c37f30437b6a4e184035ae320c912f';
const BR_FIXED = 'G/8PQJ0Jdqw7iKscX8IoiIEbLtWHqAO5VhgZbMCRBpTyOMQ/uAu4pZDkDz952HbOgek1IrSS+TCe/67L29VZrV+EHWfexWbYrDs6JqEot+7sDadxP11c4S+7bLjCXbJLneIudLtdDyEdt9XJDl3rPt0oYapcHH7WHd1OwqPY+iFVDkhDGgJEEEEMMWQggQTyIQtZyEEVVEE1FFBACUpQhhqogQrUh/pQC3VQh1w=';
const ZSTD_FIXED = 'KLUv/WAAD/UFAIKMHRWgGzpAm0/n/wBwokw77SSTLK/YjAHr3dV6F0553Y/EpKyT6o2mYflGbe2ek5S/9ExcpN4drXThzDv2Y5mcdZZ6s4mwfG1p95Bk/nIzl4v0uyurXTjkbT+SCVnn1AMIHgYFIdBoHBiLhKIQWDgcCMOAEHCtCyxDqBEgZLv7d/B15jIIMAgYBP8Owf8Nfx9yrOjoskJbV3Rn0BVdqSNbaFviaE3dIld1VHJCXVopK3JVD9AgaxYXTS0zAAE=';
const BOMB_LINE = 'badhttp compress bomb: this line repeats to the declared size'.padEnd(LINE - 1, '.').slice(0, LINE - 1) + '\n'; // exactly 64 bytes
const BOMB_DEFAULT_MIB = 8;
// SHA-256 of BOMB_LINE repeated to N MiB, generated by scripts/compress-bomb-sha.mjs (regenerate if BOMB_LINE changes).
const BOMB_SHA256 = {
  1: '1c9c3ee07a34ded0c7135ec6aef57d017d91065e259969d1138113e202ffb068',
  2: '2295fe01eeea32f741c3d8a0b3e986f0f9a5002be5b9d4e47cccf20f613a7815',
  3: '40432733c1553d16b7c29abc9d6a4aad35fca97150a0d3133eb254c446c79031',
  4: '56a824bad4bcb8d763fd1350d0a70c04b7b5509dddfa44e1d76bcc3328b5fcf9',
  5: '05d99e6f88784c047a0e5313f426970104b33483f54a8b0717d31b311a0494ce',
  6: 'd0119aba6e65d09e7c582f6d60dabd2ae74cdadfbe1db386ee1ad48a49cafc42',
  7: '5b4dce03363cb2b94036d73d3a910526376cc3509f6e6dce8752247b2980906a',
  8: 'b725e7851738cfb5e2b16744452b75d5fea9cd70c371aedfc976b80ee66103e2',
  9: '2ab72e91bf8ac6245342f70754a789039be3f19a9fa3ff38377f968799ebea2a',
  10: '1cc1675311db497dee3e355669478b7bd638c83f0c456e1ef783981153184646',
  11: 'd02d7ce05ed75ac65d9e9c58c95a593e14b50128a84762ee4252a02a7a9af704',
  12: '438b1149457a4f3679680bf77adf9fb600e52a7810b28be9474b6d226dfc52ef',
  13: '987c18f4e4da50c1123eb684f925e007555f3947d23bb2b2e6446d3397edd91f',
  14: 'eb88748c34875ab51a45725c35ff8c2c75ea6cf74499f717871fe776541ad7ca',
  15: 'e61b7f5a8f3857665b3c524d8127db4efc0e08a794d73b6e677d293f47d230d3',
  16: '0d062eeb305a596b241af927170ee3480ad7f6bab4e5ecb56ba56834476beb37',
  17: 'aa338e4ff48c3e7e8982c42b4ca418d65dd4d6dcb5e174bd50979f3f3cc4313c',
  18: '96f570d0ec8d7269246dcac796b3b20e9b01189454addb61faa51e1c15034d33',
  19: 'a3cba0650bf803bd40a70266e71191637bb0dff8dfbe93ea8ca8681b5876ee77',
  20: '99b256ee49e65c1f5b6fe9b30997e98da101229e20a481175dc3eb7d1a3416aa',
  21: '00a512adf18da037e2165ec1822078ab52a40538bc96f41e4853e902e69bb078',
  22: '0b1b63e474a8600a9ff399985baf1a37ed97a6af213e509ff763d1c0c2c25f14',
  23: 'aa632f79668a99bd2248f3f73c4b69260b981fa27af4da9eb71d6c09d40f9f9a',
  24: '52cfd8d9c9e232808b963d4bdc0d4dc54bf0ab1597d4cc1946943655ff26b90d',
  25: '135dbf2c4aea6e2bcc7e8c5d03421e96be61e04f58368f290461290a891b54bf',
  26: '5e2c2947b5269d933daf4ee931277b1b1483bdd51df024c094126324b38ad07f',
  27: '05d720f7359b3897be515c2d14db9722b74916395128a0efcd5aca90dd20866f',
  28: '7079e6d092102c0746483fa83928d5af28485543f0f6d90e269ff9c88e84bc25',
  29: '5646c755ad05176d3894eb29e6f15b2ffe8c29c9038f460f561face23f8e142f',
  30: '684e8b7cef5a54cdc6f37c6b12527942aabb913ee5ff73648c67cc2426395486',
  31: '8f485455cf2de4d8fdc8dcb33d338a1738da70e4f22c62da2d12648e02af661b',
  32: '4efe369655e0867e73b4b421aa66cba66f7a9cc19e5cf09ba3764d954b50828b',
};
// wrong-length needs a gzip member SHORTER than the plaintext it claims to be; below ~52 bytes gzip framing
// makes it longer, and FixedLengthStream would reject the write (an edge 502, found in review). 128 is safe.
const WRONG_LENGTH_MIN = 128;
const TRAILING_GARBAGE = '\nbadhttp: trailing garbage after the gzip member\n';
const EMPTY_SHA256 = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
const PROBED = '2026-09-01';

const enc = new TextEncoder();
const b64 = (s) => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));

// Line k reads "{offset:08d} {length:08d} badhttp compress body" padded with '.' to 63 chars, then "\n";
// the document is cut at length. All ASCII, so string length == byte length.
export function plainDoc(length) {
  let out = '';
  for (let off = 0; off < length; off += LINE) {
    out += `${String(off).padStart(8, '0')} ${String(length).padStart(8, '0')} badhttp compress body`.padEnd(LINE - 1, '.') + '\n';
  }
  return out.slice(0, length);
}

async function sha256hex(bytes) {
  const d = await crypto.subtle.digest('SHA-256', bytes);
  return [...new Uint8Array(d)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

async function encode(bytes, format) { // 'gzip' | 'deflate' (zlib-wrapped) | 'deflate-raw'
  const stream = new Blob([bytes]).stream().pipeThrough(new CompressionStream(format));
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

function concat(...parts) {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.byteLength, 0));
  let off = 0;
  for (const p of parts) { out.set(p, off); off += p.byteLength; }
  return out;
}

// Single-flight memo of promises for the artifacts a flood would otherwise recompute (the gzip of the
// default and maximum documents, and each bomb size — at most 34 keys, ~3 MB). Other lengths are computed
// per request and not kept.
const MEMO = new Map();
function memo(key, fn) {
  if (!MEMO.has(key)) MEMO.set(key, fn().catch((e) => { MEMO.delete(key); throw e; }));
  return MEMO.get(key);
}

async function bombBytes(mib) {
  const chunk = new Uint8Array(65536); // 1,024 copies of the 64-byte line
  const line = enc.encode(BOMB_LINE);
  for (let i = 0; i < 1024; i++) chunk.set(line, i * LINE);
  const total = mib * 1048576;
  let sent = 0;
  const src = new ReadableStream({
    pull(c) {
      if (sent >= total) { c.close(); return; }
      c.enqueue(chunk.slice());
      sent += chunk.byteLength;
    },
  });
  return new Uint8Array(await new Response(src.pipeThrough(new CompressionStream('gzip'))).arrayBuffer());
}

// The client's Accept-Encoding as the edge reports it (request.cf.clientAcceptEncoding): already a
// normalized set — no q-values, no "*", aliases folded — so parsing is a split. The q handling exists only
// so the function is correct on a raw header (RFC 9110 §12.4.2 qvalue grammar); nothing in production
// ever hands it one. null = the client sent none, or only things the edge dropped.
export function parseAcceptEncoding(header) {
  if (header === null || header === undefined) return null;
  const m = new Map();
  for (const part of header.split(',')) {
    const [tok, ...params] = part.trim().split(';');
    const name = tok.trim().toLowerCase();
    if (!name) continue;
    let q = 1;
    for (const p of params) {
      const mm = /^\s*q\s*=\s*(0(?:\.\d{0,3})?|1(?:\.0{0,3})?)\s*$/i.exec(p);
      if (mm) q = Number(mm[1]);
    }
    m.set(name === 'x-gzip' ? 'gzip' : name, q);
  }
  return m;
}

// 'gzip' when the set names it with q > 0, else 'identity'. (An RFC-perfect server would 406 when identity
// is refused as well; a refusal cannot reach this server — the edge drops q=0 entries — so it never does.)
export function negotiate(map) {
  if (map === null) return 'identity';
  const g = map.has('gzip') ? map.get('gzip') : map.has('*') ? map.get('*') : 0;
  return g > 0 ? 'gzip' : 'identity';
}

// about: what a client that advertises the coding receives, byte for byte. edge: what the edge made of it
// for a client that did not advertise gzip (curl's default, Python's urllib) — observed on 2026-09-01 at the
// default 4096-byte document unless a length is named, and pinned by scripts/smoke.sh.
// param: 'length' (?length= and ?code=), 'fixed' (?code=; ?length= only at the fixed length), 'size' (bomb).
export const COMPRESS = {
  'ok': {
    about: 'The control: gzip if the set the edge reports for you lists gzip, identity otherwise (that set reads no header, "*" and an empty value as nothing); Vary: Accept-Encoding; a correct Content-Length as sent; and the plaintext\'s length and SHA-256 in x-badhttp-plain-bytes / x-badhttp-plain-sha256 so you can prove what you decoded. q-values are already dropped from that set, so gzip;q=0 still gets gzip and identity;q=0 cannot produce a 406 from here; x-badhttp-negotiated-from shows the set.',
    edge: 'Nothing to transcode: a client that did not list gzip is sent identity by this Worker itself — unless it refused gzip with q=0, which the edge reports as listing it, and then it gets gzip.',
    param: 'length',
  },
  'br': { about: `Brotli (RFC 7932), pre-computed for the default ${FIXED_LENGTH}-byte document because this runtime has no brotli encoder; ?length= is accepted only at ${FIXED_LENGTH}.`, edge: 'Delivered only to a client whose Accept-Encoding lists br; decoded to identity for everyone else, Content-Encoding removed and Content-Length dropped.', param: 'fixed' },
  'zstd': { about: `Zstandard (RFC 8878), the newest coding browsers advertise and one several SDKs still cannot decode. Pre-computed for the default ${FIXED_LENGTH}-byte document; ?length= is accepted only at ${FIXED_LENGTH}.`, edge: 'Delivered only to a client whose Accept-Encoding lists zstd (the edge honours that even though it drops zstd from the set it reports to this Worker); decoded to identity for everyone else.', param: 'fixed' },
  'deflate': { about: 'Content-Encoding: deflate done right: a zlib stream (RFC 1950 around RFC 1951), which is what the coding name means. No client probed on 2026-09-01 received it through this host — Cloudflare\'s edge, the CDN in front of this Worker, decoded it for every one of them, even one that asked for it (GET /compress → edge_transcoding has the per-flavor list) — and the flavor exists so that observation stays reproducible.', edge: 'Decoded to identity for every client probed on 2026-09-01, including one that sent Accept-Encoding: deflate — the only coding among those probed that no client received.', param: 'length' },
  'not-compressed': { about: 'Content-Encoding: gzip on a body that is not compressed — plain text, the case most often reported in the wild (a proxy or framework that sets the header without compressing). A decoder that trusts the header fails on the first byte; some clients fall back to the raw body, some do not.', edge: 'Cannot decode it, so it removes the header and delivers the text: a client without gzip sees a correct response.', param: 'length' },
  'undeclared': { about: 'The mirror image: the body IS gzip (starts 1f 8b) but there is no Content-Encoding header at all — text/plain says it is text. A client that trusts the headers hands you binary; a few sniff the magic bytes.', edge: 'Nothing to transcode: everyone gets the gzip bytes labelled as text.', param: 'length' },
  'truncated': { about: 'A valid gzip stream cut at about 60% (x-badhttp-wire-bytes-of says exactly) — inside the DEFLATE data, before the CRC-32 and length trailer. Content-Length matches the bytes actually sent, so the transport looks complete; only the decoder can tell. Does your client report the error, or return the partial plaintext as if it were everything?', edge: 'Inflates what it can and ends the body cleanly: a 200 with the partial plaintext (1,860 of 4,096 bytes at the default length; a correct prefix of 628,228 bytes at 1 MiB) and no error anywhere. For a document of a few bytes the partial text may be all of it.', param: 'length' },
  'corrupt': { about: 'A gzip stream with up to four bytes flipped in the middle of the DEFLATE data (x-badhttp-flipped-bytes says how many and where; fewer only for streams under 25 bytes). A decoder either rejects the stream outright, or inflates it — often to the full length, correct up to the damage and garbage after — and then fails the CRC; a decoder that does not check the CRC (see bad-crc) returns that garbage with no error at all. Either way it may have handed you some of the garbage first.', edge: 'At the default length, a 200 with an EMPTY body: the decode fails, nothing is sent, no error anywhere. At 1 MiB it streamed the correct plaintext up to the damage and garbage after it, 60 bytes short, still no error — the CRC-skipping outcome.', param: 'length' },
  'bad-crc': { about: 'A gzip stream whose DEFLATE data is intact but whose CRC-32 trailer is wrong (the ISIZE is right). Every byte of plaintext is recoverable; the question is whether your client checks the checksum, and what it does with the data it already delivered when the check fails at the very end.', edge: 'Does not check the trailer: the full plaintext, no error.', param: 'length' },
  'trailing-garbage': { about: 'A complete, valid gzip member followed by 49 bytes of junk, all counted in Content-Length. RFC 1952 says a stream is a series of members; the junk is not one. Some decoders ignore it, some fail after having produced the whole plaintext, some warn.', edge: 'The full plaintext; the junk is dropped without a word.', param: 'length' },
  'multi-member': { about: 'Two gzip members back to back, each holding half the document — valid per RFC 1952 §2.2, and what some servers and concatenating CDNs really emit. Some HTTP clients decode only the first member and return half the document with no error (httpx and Ruby\'s Net::HTTP among them, 2026-09-01).', edge: 'The first member only — half the document (2,048 of 4,096 bytes at the default length), no error.', param: 'length' },
  'double': { about: 'Content-Encoding: gzip, gzip — the document gzipped twice, with both codings declared in order, exactly as RFC 9110 §8.4 allows. Clients that apply only the first coding hand you a gzip stream and call it text; clients that compare the header to "gzip" exactly do not decode at all.', edge: 'Removes exactly one layer and relabels the rest Content-Encoding: gzip — self-consistent (the header still matches the body), though RFC 9110 §7.7 forbids the transformation under no-transform, and the one case where the edge itself hands a client a coding it recognizes that the client never listed.', param: 'length' },
  'double-hidden': { about: 'The document gzipped twice but Content-Encoding says gzip once. Decoding "succeeds" and yields 1f 8b…: a gzip stream where your text should be. The bug proxies that compress already-compressed responses produce.', edge: 'Removes one layer and the header: gzip bytes labelled as text.', param: 'length' },
  'deflate-raw': { about: 'Content-Encoding: deflate with a raw RFC 1951 stream — no zlib header, no Adler-32 — the historic mistake that made "deflate" untrustworthy. Some clients detect the missing wrapper and recover; some fail on byte one; some do not decode deflate at all.', edge: 'Cannot inflate it: the raw bytes go through with the header removed. Only a client whose reported set lists gzip gets them with the header intact; listing deflate does not help — the header is removed for that client too.', param: 'length' },
  'unknown-coding': { about: 'Content-Encoding: badhttp, a coding that does not exist, on a plain-text body. There is no rule for a client here: pass the bytes through, or refuse. Which does yours do, and does it tell you?', edge: 'Unrecognized, so untouched: everyone gets it as sent.', param: 'length' },
  'uppercase': { about: 'Content-Encoding: GZIP. Coding names are case-insensitive (RFC 9110 §8.4.1); the body is ordinary gzip. Clients that compare the header case-sensitively leave it compressed.', edge: 'Recognized: decoded to identity for a client without gzip.', param: 'length' },
  'x-gzip': { about: 'Content-Encoding: x-gzip, the legacy alias that RFC 9110 §8.4.1.3 says a recipient SHOULD treat as gzip. The body is ordinary gzip.', edge: 'Not recognized as gzip: passed to everyone as sent, header and all, whatever they advertised.', param: 'length' },
  'empty': { about: 'Content-Encoding: gzip on a zero-byte body (Content-Length: 0) — what a proxy that strips a body but not its headers produces; with ?code=502 it is the stripped error page. An empty string is not a gzip stream; some decoders say so, some return nothing quietly. ?length= is accepted only at 0.', edge: 'Header removed, Content-Length: 0.', param: 'fixed', empty: true },
  'wrong-length': { about: `A correct gzip body whose Content-Length is the plaintext's length, not the wire's — the header a proxy leaves behind when it compresses without recounting. The declared bytes never arrive: the connection closes early (HTTP/1.1) or the stream is reset (HTTP/2), after the decoder has already seen a complete gzip stream. Which error do you get, if any? ?length= is at least ${WRONG_LENGTH_MIN} here, so the gzip member is really shorter than the length it claims.`, edge: 'Decodes and re-chunks: the lie disappears and a client without gzip gets a complete, correct response.', param: 'length', minLength: WRONG_LENGTH_MIN },
  'gzip-file': { about: 'The .gz download trap: a file that already IS gzip, served as a download (Content-Type: application/gzip, Content-Disposition: attachment; filename="badhttp-compress.txt.gz") — and, wrongly, with Content-Encoding: gzip as well, the way misconfigured static servers and object stores label .tar.gz files. A client that applies transport decoding saves the plaintext under a .gz name: silent corruption of the download. x-badhttp-wire-sha256 is the hash of the bytes that should land in the file; x-badhttp-plain-sha256 the hash of what lands if the client decoded.', edge: 'Commits the corruption itself: a client without gzip receives the plaintext, still labelled application/gzip with the .gz filename, Content-Encoding and Content-Length removed (observed 2026-09-02).', param: 'length' },
  'bomb': { about: `A decompression bomb, declared: one gzip member that inflates to ?size= MiB (default ${BOMB_DEFAULT_MIB}, max 32) from about 3 KB per MiB on the wire (x-badhttp-wire-bytes says exactly) — the same 64-byte line repeated. Only the requester's own memory is at risk: a client that decodes without a size limit allocates the whole thing. x-badhttp-plain-bytes states the inflated size, x-badhttp-plain-line carries the line without its newline (63 characters; the plaintext is that line plus a newline, repeated), and x-badhttp-plain-sha256 is the hash of the whole.`, edge: 'Not served: a client whose reported set lacks gzip gets a 406 asking for Accept-Encoding: gzip. That set reads as empty for a client that sent no Accept-Encoding at all, or only "*" — requests RFC 9110 §12.5.3 says accept gzip — so the 406 is not negotiation but a refusal: the edge would otherwise inflate the member itself and ship the whole ?size= MiB as text (observed before the 406 was added), testing no decoder.', param: 'size' },
};
function sanitizeHeaderValue(s, max = 200) {
  return String(s).replace(/[^\x20-\x7e]/g, '?').slice(0, max);
}

function paramsOf(f) {
  if (f.param === 'size') return ['size'];
  if (f.param === 'fixed') return ['code', `length (only ${f.empty ? 0 : FIXED_LENGTH})`];
  return f.minLength ? [`length (${f.minLength}–1048576)`, 'code'] : ['length', 'code'];
}

export async function handleCompress({ seg, url, request, json, bad, intParam, bodyCodeParam, withBase, limits, sleep }) {
  const flavor = seg[1];
  if (seg.length > 2) return json({ error: 'not found', hint: '/compress/{flavor}; GET /compress lists the flavors' }, 404);
  const cfAE = request.cf && typeof request.cf.clientAcceptEncoding === 'string' && request.cf.clientAcceptEncoding !== '' ? request.cf.clientAcceptEncoding : null;
  const hdrAE = request.headers.get('accept-encoding');
  if (!flavor) {
    // no-transform on the index too: its readers are told to send Accept-Encoding: gzip, and without it the
    // edge would hand them the index compressed (in brotli for a browser-like value).
    return json({
      flavors: Object.fromEntries(Object.entries(COMPRESS).map(([k, v]) => [k, v.about])),
      edge_transcoding: Object.fromEntries(Object.entries(COMPRESS).map(([k, v]) => [k, v.edge])),
      params: Object.fromEntries(Object.entries(COMPRESS).map(([k, v]) => [k, paramsOf(v)])),
      usage: '/compress/{flavor}?length=4096&code=200',
      document: `Deterministic and self-describing: ${LINE}-byte lines, each "{offset:08d} {length:08d} badhttp compress body" padded with dots to 63 characters plus a newline; the document is cut at ?length= (default ${DEFAULT_LENGTH}, max ${limits.compressMaxBytes}; wrong-length needs at least ${WRONG_LENGTH_MIN}). br and zstd are fixed at ${FIXED_LENGTH} bytes and empty at 0 (?length= accepted only at that value); bomb takes ?size= in MiB (1–${limits.compressBombMaxMiB}, default ${BOMB_DEFAULT_MIB}) instead. ?code= (200–599, not 204/205/304) sets the status on every flavor but bomb: a compressed or mislabelled error body is its own bug class.`,
      verification: 'Every flavor response carries x-badhttp-plain-bytes and x-badhttp-plain-sha256 for the plaintext (bomb\'s hash comes from a table; gzip-file adds x-badhttp-wire-sha256 for the bytes a download should keep): decode the body, then compare length and SHA-256. A decoder that returns the wrong bytes without an error is the finding.',
      accept_encoding: {
        as_the_edge_reports_it: cfAE,
        as_seen_by_this_worker: hdrAE,
        note: 'The edge — Cloudflare\'s CDN, between you and this Worker — rewrites Accept-Encoding to "gzip, br" before this Worker runs and keeps your value in request.cf.clientAcceptEncoding, normalized: a canonical set in a fixed order, q-values dropped (q=0 included), x-gzip and case folded to gzip, "*" and an empty value reported as absent (null), a value containing any non-ASCII byte reported as absent, and zstd dropped from the set entirely (zstd alone reads as absent; "gzip, zstd" as "gzip") even though the edge delivers zstd to a client that lists it. /compress/ok and /compress/bomb negotiate from that set; the raw header (always "gzip, br" here) is shown but never used.',
      },
      edge: {
        note: 'The edge removes one coding layer it recognizes (gzip, br, zstd) unless the normalized set above lists it (q=0 counts as listing), transcoding the body to identity, cache-control: no-transform notwithstanding — lossily for broken streams; a second declared layer (double) is delivered regardless. It decoded zlib deflate for every client probed, including one that asked for it. It passes codings it does not recognize (x-gzip, badhttp) through untouched. edge_transcoding says what each flavor became for a client without gzip, at the default length unless a length is named. Send Accept-Encoding: gzip (br, zstd for those flavors) to receive the bytes as this Worker sent them.',
        probed: PROBED,
        observations: 'What six real clients and two non-decoding controls did with every flavor here, one row per observation, dated 2026-09-02: GET /clients.jsonl (index at GET /clients). Each row joins back to a /corpus.jsonl row by corpus_id.',
      },
      encodings: { gzip: 'computed per request (CompressionStream)', deflate: 'computed per request, zlib-wrapped as the coding requires — decoded by the edge for every client probed (2026-09-01)', 'deflate-raw': 'computed per request', br: `pre-computed for the ${FIXED_LENGTH}-byte document`, zstd: `pre-computed for the ${FIXED_LENGTH}-byte document` },
      headers: 'Every flavor response is text/plain; charset=utf-8 (gzip-file: application/gzip) with cache-control: no-store, no-transform (without no-transform the edge would also compress the plain-text flavors); this index is no-transform too; error replies are ordinary JSON (no-store) that the edge may compress. HEAD returns the GET\'s headers and Content-Length as this Worker sends them; on HEAD the edge strips Content-Length and Content-Encoding from any response labelled with a coding it recognizes (gzip, br, zstd) that your reported set does not list — even not-compressed, which it delivers intact on GET — while x-gzip and badhttp keep both.',
      limits: { max_length_bytes: limits.compressMaxBytes, wrong_length_min_bytes: WRONG_LENGTH_MIN, bomb_max_mib: limits.compressBombMaxMiB },
      spec: 'RFC 9110 §8.4 and §12.5.3; RFC 1950, 1951, 1952; RFC 7932 (br); RFC 8878 (zstd)',
    }, 200, { 'cache-control': 'no-store, no-transform' });
  }
  const f = Object.hasOwn(COMPRESS, flavor) ? COMPRESS[flavor] : undefined;
  if (!f) return json({ error: 'unknown flavor', flavors: Object.keys(COMPRESS) }, 404);
  if (request.method !== 'GET' && request.method !== 'HEAD') {
    return json({ error: 'method not allowed', hint: 'GET /compress/{flavor}, HEAD for the headers' }, 405, { allow: 'GET, HEAD, OPTIONS' });
  }
  const fixedLength = f.empty ? 0 : FIXED_LENGTH;
  if (f.param === 'size' && url.searchParams.has('length')) return bad('length is not accepted here', 'bomb takes ?size= in MiB');
  if (f.param === 'fixed' && url.searchParams.has('length') && url.searchParams.get('length') !== String(fixedLength)) return bad('length is fixed here', `${flavor} serves a fixed ${fixedLength}-byte document; omit ?length= or send ?length=${fixedLength}`);
  if (f.param !== 'size' && url.searchParams.has('size')) return bad('size is not accepted here', 'only bomb takes ?size=; the others take ?length= in bytes');
  if (f.param === 'size' && url.searchParams.has('code')) return bad('code is not accepted here', 'bomb is always a 200 (or a 406 without gzip); every other flavor takes ?code=');
  let length = f.param === 'fixed' ? fixedLength : DEFAULT_LENGTH;
  if (f.param === 'length') {
    const min = f.minLength || 1;
    const p = intParam(url.searchParams.get('length') ?? String(DEFAULT_LENGTH), { min, max: limits.compressMaxBytes, name: 'length' });
    if (p.error) return bad(p.error, `?length=${DEFAULT_LENGTH} (${min > 1 ? `${flavor} needs at least ${min}; ` : ''}max ${limits.compressMaxBytes})`);
    length = p.value;
  }
  let status = 200;
  if (f.param !== 'size') {
    const c = bodyCodeParam(url.searchParams.get('code'));
    if (c.error) return bad(c.error, '?code=502 to test your error path (200–599; not 204, 205 or 304)');
    status = c.value;
  }
  let mib = BOMB_DEFAULT_MIB;
  if (f.param === 'size') {
    const p = intParam(url.searchParams.get('size') ?? String(BOMB_DEFAULT_MIB), { min: 1, max: limits.compressBombMaxMiB, name: 'size' });
    if (p.error) return bad(p.error, `?size=${BOMB_DEFAULT_MIB} (MiB, max ${limits.compressBombMaxMiB})`);
    mib = p.value;
  }

  const base = { 'content-type': 'text/plain; charset=utf-8', 'cache-control': 'no-store, no-transform', 'x-badhttp-flavor': flavor };
  // encodeBody: 'manual' tells the runtime the body already carries the coding named in Content-Encoding
  // (or none), so it must neither compress nor decompress it here. What the edge does afterwards is above.
  const reply = ({ encoding = null, body, headers = {}, plainBytes, plainSha, declaredLength }) => {
    const h = withBase({ ...base, ...headers, 'x-badhttp-plain-bytes': plainBytes, 'x-badhttp-plain-sha256': plainSha });
    if (encoding !== null) h.set('content-encoding', encoding);
    if (request.method === 'HEAD') {
      h.set('content-length', String(declaredLength ?? body.byteLength));
      return new Response(null, { status, headers: h, encodeBody: 'manual' });
    }
    return new Response(body, { status, headers: h, encodeBody: 'manual' });
  };

  if (f.empty) return reply({ encoding: 'gzip', body: new Uint8Array(0), plainBytes: 0, plainSha: EMPTY_SHA256 });

  if (f.param === 'size') {
    // Only to a client the edge will deliver gzip to: for anyone else the edge would inflate the member
    // itself and ship ?size= MiB of text, testing nothing (review finding, 2026-09-01). That includes a client
    // that sent no Accept-Encoding or "*", which RFC 9110 §12.5.3 would let receive gzip — this is a refusal,
    // not negotiation, and the hint says so.
    if (negotiate(parseAcceptEncoding(cfAE)) !== 'gzip') {
      const reported = cfAE === null ? 'nothing — no Accept-Encoding, or only "*" or an empty value, which the edge reports as absent' : `"${sanitizeHeaderValue(cfAE)}"`;
      return json({
        error: 'not acceptable',
        hint: `send Accept-Encoding: gzip. The set the edge reports for you (${reported}) does not list gzip. RFC 9110 §12.5.3 would let a request with no Accept-Encoding, or "*", receive gzip anyway — but the edge in front of this Worker would then inflate the bomb for you and deliver ${mib} MiB of plain text, which tests no decoder, so this server refuses instead.`,
        size_mib: mib,
      }, 406, { vary: 'Accept-Encoding', 'cache-control': 'no-store, no-transform', 'x-badhttp-flavor': flavor });
    }
    const body = await memo(`bomb:${mib}`, () => bombBytes(mib));
    return reply({ encoding: 'gzip', body, plainBytes: mib * 1048576, plainSha: BOMB_SHA256[mib], headers: { 'x-badhttp-plain-line': BOMB_LINE.slice(0, -1), 'x-badhttp-wire-bytes': body.byteLength, vary: 'Accept-Encoding' } });
  }

  const plain = enc.encode(plainDoc(length));
  const plainSha = length === FIXED_LENGTH ? FIXED_SHA256 : await sha256hex(plain);
  const common = { plainBytes: length, plainSha };
  const gz = () => (length === DEFAULT_LENGTH || length === limits.compressMaxBytes ? memo(`gzip:${length}`, () => encode(plain, 'gzip')) : encode(plain, 'gzip'));

  switch (flavor) {
    case 'ok': {
      const choice = negotiate(parseAcceptEncoding(cfAE));
      const vary = { vary: 'Accept-Encoding', 'x-badhttp-negotiated-from': cfAE === null ? '(none: no Accept-Encoding, or nothing the edge kept)' : sanitizeHeaderValue(cfAE) };
      if (choice === 'identity') return reply({ body: plain, headers: vary, ...common });
      return reply({ encoding: 'gzip', body: await gz(), headers: vary, ...common });
    }
    case 'br':
      return reply({ encoding: 'br', body: b64(BR_FIXED), ...common });
    case 'zstd':
      return reply({ encoding: 'zstd', body: b64(ZSTD_FIXED), ...common });
    case 'deflate':
      return reply({ encoding: 'deflate', body: await encode(plain, 'deflate'), ...common });
    case 'not-compressed':
      return reply({ encoding: 'gzip', body: plain, ...common });
    case 'undeclared':
      return reply({ body: await gz(), ...common });
    case 'truncated': {
      const g = await gz();
      const cut = Math.min(Math.max(11, Math.floor(g.byteLength * 0.6)), g.byteLength - 9); // inside the DEFLATE data
      return reply({ encoding: 'gzip', body: g.slice(0, cut), headers: { 'x-badhttp-wire-bytes-of': `${cut} of ${g.byteLength}` }, ...common });
    }
    case 'corrupt': {
      const g = (await gz()).slice();
      let start = 10 + Math.floor((g.byteLength - 18) / 2);
      let n = Math.min(4, g.byteLength - 8 - start);
      if (n <= 0) { start = 10; n = Math.max(1, g.byteLength - 18); }
      for (let i = 0; i < n; i++) g[start + i] ^= 0xff;
      return reply({ encoding: 'gzip', body: g, headers: { 'x-badhttp-flipped-bytes': `${n} at offset ${start}` }, ...common });
    }
    case 'bad-crc': {
      const g = (await gz()).slice();
      g[g.byteLength - 8] ^= 0xff; // first byte of the CRC-32 trailer; ISIZE untouched
      return reply({ encoding: 'gzip', body: g, ...common });
    }
    case 'trailing-garbage': {
      const g = await gz();
      const junk = enc.encode(TRAILING_GARBAGE);
      return reply({ encoding: 'gzip', body: concat(g, junk), headers: { 'x-badhttp-wire-bytes-of': `${g.byteLength} of gzip, then ${junk.byteLength} of garbage` }, ...common });
    }
    case 'multi-member': {
      const half = Math.ceil(length / 2);
      const [a, b] = await Promise.all([encode(plain.slice(0, half), 'gzip'), encode(plain.slice(half), 'gzip')]);
      return reply({ encoding: 'gzip', body: concat(a, b), headers: { 'x-badhttp-members': `2 (${half} + ${length - half} plaintext bytes)` }, ...common });
    }
    case 'double':
      return reply({ encoding: 'gzip, gzip', body: await encode(await gz(), 'gzip'), ...common });
    case 'double-hidden':
      return reply({ encoding: 'gzip', body: await encode(await gz(), 'gzip'), ...common });
    case 'deflate-raw':
      return reply({ encoding: 'deflate', body: await encode(plain, 'deflate-raw'), ...common });
    case 'unknown-coding':
      return reply({ encoding: 'badhttp', body: plain, ...common });
    case 'uppercase':
      return reply({ encoding: 'GZIP', body: await gz(), ...common });
    case 'x-gzip':
      return reply({ encoding: 'x-gzip', body: await gz(), ...common });
    case 'gzip-file': {
      const g = await gz();
      return reply({ encoding: 'gzip', body: g, headers: { 'content-type': 'application/gzip', 'content-disposition': 'attachment; filename="badhttp-compress.txt.gz"', 'x-badhttp-wire-sha256': await sha256hex(g), 'x-badhttp-wire-bytes': g.byteLength }, ...common });
    }
    case 'wrong-length': {
      const g = await gz();
      // The member must be shorter than the length it claims, or FixedLengthStream rejects the write and the
      // edge answers with its own 502. WRONG_LENGTH_MIN makes this unreachable; the guard keeps it so.
      if (g.byteLength >= length) return bad('length is too small for wrong-length', `the gzip member (${g.byteLength} bytes) must be shorter than the plaintext it claims to be; use ?length=${WRONG_LENGTH_MIN} or more`);
      const h = withBase({ ...base, 'content-encoding': 'gzip', 'x-badhttp-plain-bytes': length, 'x-badhttp-plain-sha256': plainSha, 'x-badhttp-wire-bytes': g.byteLength });
      if (request.method === 'HEAD') {
        h.set('content-length', String(length));
        return new Response(null, { status, headers: h, encodeBody: 'manual' });
      }
      // FixedLengthStream makes the runtime declare Content-Length: length (the plaintext size); aborting the
      // writer after the real gzip bytes makes it drop the connection instead of finishing — as /truncate does.
      const { readable, writable } = new FixedLengthStream(length);
      const writer = writable.getWriter();
      (async () => {
        try {
          await writer.write(g);
          await sleep(100);
          await writer.abort(new Error('badhttp: wrong-length on purpose'));
        } catch (e) {
          // the client may have gone away first
        }
      })();
      return new Response(readable, { status, headers: h, encodeBody: 'manual' });
    }
    default:
      return json({ error: 'unknown flavor', flavors: Object.keys(COMPRESS) }, 404);
  }
}
